import pandas as pd
du_lieu = pd.read_csv("creditcard.csv")
print("Kích thước dữ liệu:", du_lieu.shape)
print("\n5 dòng đầu tiên:")
print(du_lieu.head())
print("\nThông tin chi tiết:")
print(du_lieu.info())
print("\nThống kê mô tả:")
print(du_lieu.describe())
print("\nGiá trị bị thiếu:")
print(du_lieu.isnull().sum())
print("\nPhân bố nhãn (Class):")
print(du_lieu['Class'].value_counts())
ty_le_gian_lan = (du_lieu['Class'].value_counts()[1] / len(du_lieu)) * 100
print(f"\nTỷ lệ giao dịch gian lận: {ty_le_gian_lan:.4f}%")
